Manweill/swagger-axios-codegen

src/baseInterfaces.ts
src/requestCodeGen.ts

This fixes an issue where the following schema would result in an error.
```
"parameters": [
{
"name": "value",
"in": "body",
"required": false,
"schema": {
"type": "string"
}
}
]
```

Fixed bug where schema.type would not be recognised

---

src/requestCodeGen.ts

In generated request function,
```ts
//...
let data = null;
data = { ...params['prop'] }
//...
```
Even though the `data` object is declared as `null` type,
it is reassigned the value that has actual type.
I don't know if it is ok on other environments but my ts3.0 project got some errors.

Fixes type error on data declaration

---

src/baseInterfaces.ts
src/requestCodeGen.ts

In some cases, we want to use primitive type as just a response data (string, boolean or number).
Example:
```js
// definition of the api "/ping"
{
// ...
responses: {
200: {
description: "Success",
schema: {
type: "string",
example: "pong"
}
}
}
// ...
}
```
At present, a definition like below generates `Primitive<any>` return value.
This PR handles such a case.

Adds support of primitive response types

---

example/package.json
example/swagger.json
example/yarn.lock
src/definitionCodegen/createDefinitionClass.ts

fix: generated type of multiple number enums are not separated
and updated example to show the error in the current version

fix: generated type of multiple number enums are not separated

---

package.json
src/requestCodegen/getRequestParameters.ts
src/requestCodegen/index.ts
src/template.ts
tsconfig.json
yarn.lock

Hi,
I solved the problem with class names (at least when using `path` parameter) mentioned in #13 .
The main issue is that type definitions for camelcase are *wrong* (or out of date, so at least currently wrong). Using a rx, as you did, is not effective.
The following is a more correct definition for [camelcase](https://github.com/sindresorhus/camelcase). You can compare against the library docs and [the "official" types definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/camelcase/index.d.ts) which is completely wrong.
```ts
declare interface ICamelCaseOptions{
pascalCase: boolean
}
declare function camelcase(args: string| string[], options?: ICamelCaseOptions): string;
```
But i didn't have success in including into the local definitions, so I just decided …

Pascal case classnames

---

src/baseInterfaces.ts
src/definitionCodegen/createDefinitionClass.ts
src/index.ts
src/requestCodegen/getResponseType.ts
src/swaggerInterfaces.ts
src/template.ts
src/utils.ts

This MR adds https://github.com/typestack/class-transformer to transform the result types. Strings, which have the a format of `date` or `date-time` are now transformed to a `Date` instance.
The default option used for class-transformer is to ignore all additional parameters. So the transformed result Object only contains the parameters defined inside the DTO or generated model and additional parameters returned by the API are ignored.
There is an option to enable class-transformer which is `false` by default and therefore it does not break any existing usage.

WIP: Add class-transformer to transform results and support dates

---

src/definitionCodegen/propTrueType.ts

When we got an enum like this in definitions : 
``` json
"ResponseEntity": {
"type": "object",
"properties": {
"body": { "type": "object" },
"statusCode": {
"type": "string",
"enum": [
"100",
"101",
]
},
"statusCodeValue": { "type": "integer", "format": "int32" }
},
"title": "ResponseEntity"
},
``` 
code generation will generate an enum like this 
``` ts
export enum EnumResponseEntityStatusCode {
'100' = '100',
'101' = '101'
}
``` 
Triggering a .ts error `An enum member cannot have a numeric name.`
The project builds and it worked for me in local. I don't have a test plan as there is no unitary tests in this package
#64

fix: enum member cannot have numeric value

---

src/componentsCodegen/propTrueType.ts
src/swaggerInterfaces.ts

Found a bug in v3. Some of property types were missing.
Reference to the documentation [allOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof)

Bug OpenApi3 Missing Property Types

---

src/requestCodegen/index.ts

Hi! 
I found a bug in methods naming.
Assume you have two methods `getUsers` and `getUser`. 
Result of 
```js
/getUser[0-9]?/.test("getUsers")
``` 
is true. Thus, the method is considered as  nonunique and has name `getUser1`.

Fixed unique method name regexp

---

src/templates/template.ts

When using `modelMode: "interface"` the `format` value from swagger always passed `null` into the `classPropsTemplate` function. It now correctly passes `p.format`.
For example, this will ensure that `format: date` will be transformed to `Date` and not `string`.
Fixes #80

fix: pass format value for modeMode: "interface", which was null #80

---

src/requestCodegen/index.ts

Merging the imports of the parameters and the body for a request pushed the body imports inside the imports array instead of adding it's elements. This way there was an array inside an array and at a later point, where the name is checked, it fails because it is an array and not a string

fix: mergining imports

---

src/componentsCodegen/propTrueType.ts

After my change with anyOf and allOf the reference types in arrays were buggy. This MR resolves the problems i think

fix: refence types in arrays were buggy after last release

---

src/requestCodegen/index.ts

requestCodegen/index.ts
In case reqProps.parameters == null (no other query params)- an exception in concat occurs

fix multipart request when no query params

---

src/baseInterfaces.ts
src/index.ts
src/requestCodegen/getRequestParameters.ts
src/requestCodegen/index.ts
src/swaggerInterfaces.ts
src/templates/template.ts

起因：在目前项目使用过程中有一些参数在请求头中 而且为必填项
目前的版本会将这些参数加入到请求接口的参数类型中
然而实际上并没有将这些参数加入到axios的请求headers中 此处为一bug
另外工作中请求头中的参数大部分都为固定参数 
所以使用新建axios实例来初始化headers中的参数，和README中展示的一样
所以在设置中增加了一个useHeaderParameters设置项
用来控制请求头中的参数是否进入接口的参数列表
目前headers的覆盖顺序为 {...requestParametersHeaders, ...requestOptionsHeaders, 'Content-type':XXX}
做了一些简单的测试，功能已经实现。
如还有遗漏的地方麻烦帮忙补充或者讨论。
（有几行的修改是由于Prettier格式导致的，如单行超过80字符，自动进行格式化了）

feature: add useHeaderParameters option

---

src/componentsCodegen/createDefinitionEnum.ts
src/componentsCodegen/propTrueType.ts
src/definitionCodegen/createDefinitionEnum.ts
src/definitionCodegen/propTrueType.ts

relates to https://github.com/Manweill/swagger-axios-codegen/pull/65
Problem: spec definition contained the following schema:
```js
{
"ReportSchema": {
"properties": {
"errorCode": {
"description": "Error code",
"enum": [
"10",
"20",
"30",
"40"
],
"example": "10",
"maxLength": 3,
"type": "string"
}
}
}
}
```
The output was not a valid TS:
```ts
export enum ReportSchemaErrorCode {
'10' = '10',
'20' = '20',
'30' = '30',
'40' = '40'
}
```
Enum keys in TS cannot be numeric.
The PR#65 fixed one of the 4 places with the enum generation. This PR fixes the other three places.
Output with this PR:
```ts
export enum ReportSchemaErrorCode {
'KEY_10' = '10',
'KEY_20' = '20',
'KEY_30' = '30',
'KEY_40' = '40'
}
```

fix: numeric enum keys are always prefixed with `KEY_`

---

example/package.json
example/swagger/codegen-customMethodNameMode.js
src/baseInterfaces.ts
src/requestCodegen/index.ts

I'm currently using [nestjs/swagger](https://github.com/nestjs/swagger) for building an API and the autogenerated `operationId` comes with not only the tag at the end but also the controller name.
**Example:** `PostsController.getMany` (Tag: Posts) => `getManyPostsControllerPosts`
#108 implemented a solution for removing the first tag from the `operationId` but I still needed the controller name to be removed.
**Generated with `shortOperationId`:** `getManyPostsController`
So I'm suggesting this change to make possible to use custom method name mode (a function) so you can implement your own.
Using a custom method name mode:
```js
methodNameMode: (reqProps) => {
let camelCaseSplit = reqProps.operationId
.replace(/([a-z])([A-Z])/g, "$1 $2")
.split(" ");
return camelCaseSplit.slice(0, …
```

add support for custom method name mode

---

src/templates/template.ts

Hi @Manweill ,
Thanks for the fix of https://github.com/Manweill/swagger-axios-codegen/issues/128
Unfortunately the remaining issue is that all props that are not transformed with class-transformer are not decorated with `@Expose()`. Meaning that this props will be accessed as `undefined` by the app because they will be excluded.
I updated the template so that this does not happen but maybe you'll come with a better solution.
Thanks.
Ronan

fix: don't exclude props of untransformed props

---

src/templates/serviceHeader.ts

Looks like `axiosStatic` isn't being used, should it be removed? If it is I'll be happy to update this PR.
My project tsconfig.json has this rule set to true: `"noUnusedLocals": true` so it throws error: axiosStatic is declared but its value is never read. The quick fix is to add `// @ts-ignore` right above the import line.

ignore unused import

---

src/templates/template.ts

Hi there,
I am using an OpenAPI3 schema generated by  DRF-Spectecular for Django. In our swagger.json we have an Enum with an empty string value. 
Our BlankEnum field on the schema:
```json
"BlankEnum": {
"enum": [
""
]
},
```
This causes the generator to write faulty TS code:
```
error SyntaxError: Type expected. (5103:27)
> 5103 |   export type BlankEnum = ;
|                           ^
```
My current fix is to change the template.ts to render an empty string with quotes and it seems to work, as the generator will do write an emtpy string with quotes in the generated TS code.
```typescript
export function typeTemplate(name: string, typeString: string, prefix?: string) {
return `
export type ${name} = ${typeString || '""'};
`
}
```
If this change is acceptable feel free to merge, would …

add quotes string fallback to typeTemplate when typeString is an an empty string

---

src/templates/template.ts

It is **not** required for a type to carry an additional **format** spec.
We are trying to import a swagger API document which does not assign a specific format to its string typed attributes.
> Primitives have an **optional** modifier property: format.
see: https://swagger.io/specification/#data-types
see also table in spec stating that: `The formats defined by the OAS are: string without any format`

fix: expose string types without a format specification

---

package.json
yarn.lock

Axios recently switched to the first major version. This upgrade had a few changes to the typings which now are stronger. This PR updates the version of axios used by swagger-axios-codegen

chore(deps): upgrade axios to 1.2.2

---

pnpm-lock.yaml
src/requestCodegen/getContentType.ts

After introducing other content types I suggest to fall back on json if it exists. For example in some cases we would have multiple contents:
``` json
"paths": {
"/Data/Address/GetAddress": {
"post": {
"tags": [
"AddressService"
],
"operationId": "GetAddress",
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/IdVm"
}
},
"application/xml": {
"schema": {
"$ref": "#/components/schemas/IdVm"
}
},
"application/x-www-form-urlencoded": {
"schema": {
"$ref": "#/components/schemas/IdVm"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/AddressFormVm"
}
},
"application/xml": {
"schema": {
"$ref": "#/components/schemas/AddressFormVm"
}
}
}
}
},
```
Of course …

Prefer Json over other content types

---

src/baseInterfaces.ts
src/templates/template.ts

feat: 添加响应类型包装器

---

src/templates/template.ts

Hi,
switching from 0.16.8 to 0.16.9 the generated client ignores file uploads. We have this request in swagger:
```
"requestBody": {
"required": true,
"content": {
"multipart/form-data": {
"schema": {
"type": "object",
"properties": {
"file": {
"type": "string",
"format": "binary"
}
}
}
}
}
}
```
which worked fine and generated the upload code:
Since 0.16.9 it is broken and generated nothing in this place. This breaks the file uploads for us.
We identified the change which broke the generation. It seems that the if statement is to harsh and in our case it will be skipped. We made a PR to revert this if statement change, bur we are open for other solutions. 
https://github.com/Manweill/swagger-axios-codegen/compare/v0.16.8...v0.16.9

fix: Multipart Formdata bodies are ignored

---

example/oneOf.json
example/swagger/oneOf.js
src/requestCodegen/getRequestBody.ts
src/requestCodegen/getResponseType.ts
src/swaggerInterfaces.ts

add possibility to use oneOf in response and body
