src/requestCodegen/index.ts

[feature] use `as any` in typescript generation

---

src/requestCodegen/getResponseType.ts

Fix #33 + apply prettier rules

Fix 20X status code response types

---

src/template.ts

Extend request options

---

src/template.ts

Make responseType configurable

---

src/requestCodegen/getRequestParameters.ts
src/template.ts

Fix array in response bodys

---

src/template.ts

ESLint is yelling at me about this...

chore: remove unused import

---

example/swagger/codegen.js
src/template.ts

template.ts 
customerServiceHeader

fix: useCustomerRequestInstance template

---

README.md

Adds a new example to the README.md

add documentation for the `useClassTransformer` option

---

README.md
src/baseInterfaces.ts
src/componentsCodegen/createDefinitionClass.ts
src/componentsCodegen/index.ts
src/definitionCodegen/createDefinitionClass.ts
src/definitionCodegen/index.ts
src/index.ts
src/templates/template.ts
src/utils.ts

Basic functionality of validation model described in #50

Validation Model (basics)

---

src/index.ts
src/requestCodegen/getResponseType.ts
src/requestCodegen/index.ts
src/swaggerInterfaces.ts

Reverts Manweill/swagger-axios-codegen#71

Revert "Promise result is Any instead of the actual Type in open api v3"

---

src/index.ts
src/requestCodegen/getResponseType.ts
src/requestCodegen/index.ts
src/swaggerInterfaces.ts

Related to https://github.com/Manweill/swagger-axios-codegen/issues/69

Promise result is Any instead of the actual Type in open api v3

---

.gitignore
README.md
src/baseInterfaces.ts
src/componentsCodegen/createDefinitionClass.ts
src/componentsCodegen/index.ts
src/definitionCodegen/createDefinitionClass.ts
src/definitionCodegen/index.ts
src/index.ts
src/templates/template.ts
src/utils.ts

Related to https://github.com/Manweill/swagger-axios-codegen/issues/50

Validation Model

---

src/requestCodegen/getContentType.ts
src/requestCodegen/index.ts
src/requestCodegen/mapFormDataToV2.ts
src/swaggerInterfaces.ts

https://github.com/Manweill/swagger-axios-codegen/issues/93

#93 Fix multipart/form-data generation V3

---

src/componentsCodegen/createDefinitionClass.ts
src/componentsCodegen/propTrueType.ts
src/swaggerInterfaces.ts

anyOf will create a union type which will be assigned and allOf will now create a combined type which will be assigned. It works with stand alone types and arrays

feat: add anyOf union type and allOf combined type

---

src/componentsCodegen/createDefinitionClass.ts

Generated union types will be exported like all other types are

fix: export union types

---

src/componentsCodegen/createDefinitionEnum.ts
src/definitionCodegen/createDefinitionEnum.ts

Related to #119 
Related to #115

119 - String Enums have prefix KEY

---

README.md

Some small changes (clarifications) around the Readme file.

Readme Improvement

---

README.md
src/baseInterfaces.ts
src/index.ts

Include extra types

---

README.md

Fixing README.md "include" setting

---

src/templates/serviceHeader.ts

this adds some additional options for RequestOptions. This should also close #133

add axios options for RequestOptions

---

example/swagger3.json
src/componentsCodegen/createDefinitionClass.ts
src/componentsCodegen/index.ts
src/swaggerInterfaces.ts
src/templates/template.ts

My implementation of additional properties so they can be types.

feat: support additionalProperties for top level entities

---

src/requestCodegen/getRequestParameters.ts
src/swaggerInterfaces.ts

feat(getUniqParams): Use name of $ref if v has no name

---

.gitignore
package.json
src/index.ts
src/requestCodegen/getRequestParameters.ts

Added an error message on failed load.

Add error message on load

---

src/index.ts

Please see an issue: #174 for more details.

Allow self signed certificates

---

pnpm-lock.yaml
src/templates/template.ts

 Creating objects with strong type validation #153

---

README.md
package.json
src/baseInterfaces.ts
src/requestCodegen/index.ts
src/templates/serviceHeader.ts
yarn.lock

classNameMode，当前不满足要求，添加了回调函数的形式自定义生成类名

feat: classNameMode 支持 回调函数的形式

---

src/index.ts

fix: https://github.com/Manweill/swagger-axios-codegen/issues/194

feat: support url fuzzy match

---

src/requestCodegen/index.ts
src/swaggerInterfaces.ts

parse and use path level parameters
